# Generated by Django 5.1.3 on 2024-11-13 18:51

import ControlUsuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ControlUsuarios.models.CustomUserManager()),
            ],
        ),
    ]
