# Generated by Django 5.1.3 on 2024-11-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erroresmodel',
            options={'verbose_name': 'Error', 'verbose_name_plural': 'Errores'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
