# Generated by Django 5.1.3 on 2024-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('operador', 'Operador')], default='operador', max_length=10),
        ),
    ]
