# Generated by Django 5.1.3 on 2024-11-15 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0007_alter_customuser_role'),
    ]

    operations = [
        # Asegurarse de que el campo rut_fk en la tabla 'ErroresModel' sea una relación ForeignKey con el modelo de usuario
        migrations.AlterField(
            model_name='erroresmodel',
            name='rut_fk',
            field=models.ForeignKey(
                db_column='rut_fk',  # Deja el nombre de la columna como 'rut_fk'
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,  # Relación con el modelo de usuario
            ),
        ),
    ]