# Generated by Django 5.1.3 on 2024-11-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0008_rename_rut_fk_customuser_rut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rut_fk',
            new_name='rut',
        ),
    ]
