# Generated by Django 5.1.3 on 2024-11-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0009_rename_rut_fk_customuser_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaModel',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_planta', models.CharField(max_length=100, verbose_name='Nombre de la Planta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'planta',
            },
        ),
        migrations.RemoveField(
            model_name='erroresmodel',
            name='id_turno_fk',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('operador', 'Operador'), ('administrador', 'Administrador')], default='operador', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='planta_fk',
            field=models.ForeignKey(blank=True, db_column='planta_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControlUsuarios.plantamodel', verbose_name='Planta Asociada'),
        ),
        migrations.AddField(
            model_name='erroresmodel',
            name='planta_fk',
            field=models.ForeignKey(db_column='planta_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='ControlUsuarios.plantamodel'),
        ),
    ]
