# Generated by Django 5.1.3 on 2024-11-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0010_plantamodel_remove_erroresmodel_id_turno_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='planta_fk',
            field=models.ForeignKey(blank=True, db_column='planta_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='ControlUsuarios.plantamodel', verbose_name='Planta Asociada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='erroresmodel',
            name='planta_fk',
            field=models.ForeignKey(db_column='planta_fk', on_delete=django.db.models.deletion.CASCADE, to='ControlUsuarios.plantamodel'),
        ),
        migrations.AlterField(
            model_name='plantamodel',
            name='nombre_planta',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de la Planta'),
        ),
    ]
