# Generated by Django 5.1.3 on 2024-11-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0011_alter_customuser_planta_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEnvasesModel',
            fields=[
                ('id_cfg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del envase')),
                ('valor_mask', models.IntegerField(verbose_name='Mask')),
                ('dilatation', models.IntegerField(verbose_name='Dilatation')),
                ('x_offset', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='x_offset')),
                ('y_offset', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='y_offset')),
                ('width_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Width ratio')),
                ('height_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height ratio')),
                ('date_format', models.CharField(max_length=30, verbose_name='Formato de Fecha')),
            ],
            options={
                'verbose_name': 'ConfigEnvase',
                'verbose_name_plural': 'ConfigEnvases',
                'db_table': 'configenvases',
            },
        ),
        migrations.CreateModel(
            name='RegistroAciertos',
            fields=[
                ('id_registroacierto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField(verbose_name='Cantidad total')),
                ('cantidad_perdida', models.IntegerField(verbose_name='Cantidad perdida')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('planta_fk', models.ForeignKey(db_column='planta_fk', on_delete=django.db.models.deletion.CASCADE, related_name='registros_aciertos', to='ControlUsuarios.plantamodel')),
            ],
            options={
                'verbose_name': 'Registro de Aciertos',
                'verbose_name_plural': 'Registros de Aciertos',
                'db_table': 'registroaciertos',
            },
        ),
    ]
