# Generated by Django 5.1.3 on 2024-11-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUsuarios', '0012_configenvasesmodel_registroaciertos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
